Repository grid-js/gridjs, pull requests merged in 2020-06, with the labels that each got.

#38 feat: horizonal table scroll and better autoWidth algorithm
  src/config.ts
  src/grid.ts
  src/header.ts
  src/theme/mermaid/container.scss
  src/theme/mermaid/footer.scss
  src/theme/mermaid/wrapper.scss
  src/util/width.ts
  src/view/container.tsx
  src/view/footerContainer.tsx
  src/view/headerContainer.tsx
  src/view/table/thead.tsx
  tests/view/__snapshots__/container.test.tsx.snap
Labels: new feature

#47 fix(header): using Shadow Table to calculate the columns width
  src/header.ts
  src/operator/search.ts
  src/pipeline/pipeline.ts
  src/pipeline/processor.ts
  src/row.ts
  src/storage/memory.ts
  src/storage/server.ts
  src/tabular.ts
  src/util/applyMixin.ts
  src/util/className.ts
  src/util/eventEmitter.ts
  src/util/id.ts
  src/util/width.ts
  src/view/container.tsx
  src/view/plugin/pagination.tsx
  src/view/plugin/sort/sort.tsx
  src/view/plugin/sort/store.ts
  src/view/table/shadow.tsx
  tests/storage/memory.test.ts
  tests/view/__snapshots__/container.test.tsx.snap
Labels: bug fix

#49 feat: adding column formatter
  index.ts
  src/header.ts
  src/types.ts
  src/util/applyMixin.ts
  src/util/className.ts
  src/util/html.ts
  src/view/container.tsx
  src/view/footerContainer.tsx
  src/view/headerContainer.tsx
  src/view/htmlElement.tsx
  src/view/plugin/pagination.tsx
  src/view/plugin/search/search.tsx
  src/view/plugin/sort/sort.tsx
  src/view/table/messageRow.tsx
  src/view/table/shadow.tsx
  src/view/table/table.tsx
  src/view/table/tbody.tsx
  src/view/table/td.tsx
  src/view/table/th.tsx
  src/view/table/thead.tsx
  src/view/table/tr.tsx
  tests/view/__snapshots__/container.test.tsx.snap
  tests/view/__snapshots__/table.test.tsx.snap
  tests/view/__snapshots__/td.test.tsx.snap
  tests/view/table.test.tsx
Labels: new feature

#53 fix(search): searching in HTML content
  src/operator/search.ts
  src/types.ts
  src/view/htmlElement.tsx
Labels: bug fix

#56 Adding custom compare function to the sort plugin
  src/header.ts
  src/pipeline/sort/native.ts
  src/types.ts
  src/view/plugin/sort/actions.ts
  src/view/plugin/sort/sort.tsx
  src/view/plugin/sort/store.ts
  src/view/table/th.tsx
  tests/view/container.test.tsx
  tests/view/table.test.tsx
Labels: new feature

#73 Improving accessibility
  jest.config.js
  package-lock.json
  package.json
  src/view/container.tsx
  src/view/plugin/pagination.tsx
  src/view/plugin/search/search.tsx
  src/view/plugin/sort/sort.tsx
  src/view/table/messageRow.tsx
  src/view/table/table.tsx
  src/view/table/td.tsx
  src/view/table/th.tsx
  tests/setup.ts
  tests/view/__snapshots__/container.test.tsx.snap
  tests/view/container.test.tsx
  tests/view/table/__snapshots__/container.test.tsx.snap
  tests/view/table/__snapshots__/table.test.tsx.snap
Labels: new feature, roadmap

#82 Adding `handle` callback to ServerStorage
  src/pipeline/pipeline.ts
  src/storage/server.ts
  src/theme/mermaid/pagination.scss
  src/theme/mermaid/th.scss
  src/view/container.tsx
  src/view/plugin/pagination.tsx
  tests/view/__snapshots__/container.test.tsx.snap
Labels: new feature, roadmap

#81 fix(search): regex bug when keyword contains the letter s
  src/operator/search.ts
  tests/operator/search.test.ts
Labels: bug fix

#85 Fixing shadow table
  src/config.ts
  src/grid.ts
  src/header.ts
  src/pipeline/pipeline.ts
  src/view/container.tsx
  src/view/plugin/pagination.tsx
  src/view/table/shadow.tsx
  tests/testUtil.ts
  tests/view/__snapshots__/container.test.tsx.snap
  tests/view/container.test.tsx
  tests/view/table/__snapshots__/table.test.tsx.snap
  tests/view/table/table.test.tsx
Labels: bug fix, new feature

#92 chore(Cell): fixing component datatypes
  src/cell.ts
  src/types.ts
  src/util/html.ts
  src/view/htmlElement.tsx
  tests/setup.ts
Labels: internal

#109 Data config should accept an array of objects (JSON)
  src/config.ts
  src/header.ts
  src/pipeline/pipelineUtils.ts
  src/pipeline/transformer/arrayToTabular.ts
  src/pipeline/transformer/storageResponseToArray.ts
  src/storage/memory.ts
  src/storage/storage.ts
  src/tabular.ts
  src/types.ts
  src/util/array.ts
  src/util/string.ts
  src/util/type.ts
  tests/util/array.test.ts
  tests/view/__snapshots__/container.test.tsx.snap
  tests/view/container.test.tsx
Labels: new feature, roadmap

#110 Fixing sort plugin to set the total records correctly
  src/pipeline/sort/native.ts
  src/view/plugin/pagination.tsx
Labels: bug fix

#111 fix(pipeline): clearCache() should reset the lastProcessedID to -1
  src/pipeline/pipeline.ts
  tests/pipeline/pipeline.test.ts
Labels: bug fix

#118 fix(search): checking props of element object
  src/operator/search.ts
Labels: bug fix

#120 fix(pipeline): using EventEmitter in Pipeline and PipelineProcessor
  src/pipeline/pipeline.ts
  src/pipeline/processor.ts
  src/util/trigger.ts
  src/view/container.tsx
  src/view/footerContainer.tsx
  src/view/headerContainer.tsx
  src/view/plugin/pagination.tsx
  src/view/plugin/search/search.tsx
  src/view/plugin/sort/sort.tsx
  tests/pipeline/filter/globalSearch.test.ts
  tests/pipeline/pipeline.test.ts
  tests/util/eventEmitter.test.ts
  tests/view/container.test.tsx
Labels: bug fix, internal

#119 fix(header): column should accept VNode and HTML element
  src/config.ts
  src/header.ts
  src/types.ts
  tests/view/table/__snapshots__/table.test.tsx.snap
  tests/view/table/table.test.tsx
Labels: bug fix, internal
