Repository grid-js/gridjs, pull requests merged in 2021-06, with the labels that each got.

#566 add turkish language support
  i18n/index.ts
  i18n/tr_TR.ts
Labels: new feature

#594 chore: adding the jest coverage script
  .github/workflows/coverage.yaml
  package.json
  plugins/selection/package-lock.json
  plugins/selection/package.json
  tests/dev-server/package-lock.json
Labels: internal

#595 chore: adding prettier to the test
  .prettierignore
  i18n/fr_FR.ts
  i18n/index.ts
  package-lock.json
  package.json
  plugins/selection/package-lock.json
  rollup.config.js
  src/config.ts
  src/operator/search.ts
  src/pipeline/transformer/arrayToTabular.ts
  src/util/throttle.ts
  src/view/footerContainer.tsx
  src/view/headerContainer.tsx
  src/view/plugin/resize/resize.tsx
  src/view/plugin/search/search.tsx
  tests/cypress/integration/table.spec.ts
  tests/cypress/support/commands.ts
  tests/cypress/support/index.ts
  tests/dev-server/package-lock.json
  tests/dev-server/src/index.js
  tests/dev-server/src/style.css
  tests/jest/operator/search.test.ts
  tests/jest/pipeline/pipeline.test.ts
  tests/jest/view/container.test.tsx
  tests/jest/view/plugin/search/search.test.tsx
Labels: internal

#596 chore: removing unused deps
  package-lock.json
  package.json
  plugins/selection/package-lock.json
Labels: internal

#625 chore: changing postinstall to prepare
  package-lock.json
  package.json
  plugins/selection/package-lock.json
Labels: bug fix

#619 Add new locale (ko_KR)
  l10n/index.ts
  l10n/ko_KR.ts
Labels: new feature

#638 Add new locale (pt_PT)
  l10n/index.ts
  l10n/pt_PT.ts
Labels: new feature
