Repository grid-js/gridjs, pull requests merged in 2022-06, with the labels that each got.

#1002 fix: recursive install
  .github/workflows/coverage.yaml
  .github/workflows/main.yaml
  .github/workflows/nodejs.yml
  l10n/index.ts
  package-lock.json
  package.json
Labels: bug fix, internal

#987 Fixed focus outline
  src/theme/mermaid/pagination.scss
Labels: bug fix

#977 Add Brazilian Portuguese locale/translation
  l10n/index.ts
  l10n/pt_BR.ts
Labels: new feature

#927 Add fa_IR locale
  l10n/fa_IR.ts
  l10n/index.ts
Labels: new feature

#658 Add norwegian locale (nb_NO)
  l10n/index.ts
  l10n/nb_NO.ts
Labels: new feature
