Repository grid-js/gridjs, pull requests merged in 2024-01, with the labels that each got.

#1408 Fix the multiple server-side requests bug
  src/config.ts
  src/hooks/useSelector.ts
  src/pipeline/extractor/storage.ts
  src/pipeline/pipeline.ts
  src/pipeline/processor.ts
  src/util/deepEqual.ts
  src/util/throttle.ts
  src/view/container.tsx
  src/view/plugin/pagination.tsx
  src/view/plugin/search/search.tsx
  src/view/plugin/sort/actions.ts
  src/view/plugin/sort/sort.tsx
  tests/jest/grid.test.ts
  tests/jest/util/throttle.test.ts
  tests/jest/view/container.test.tsx
Labels: bug fix

#1409 Fix the throttle function and upgrade to v6.1
  package-lock.json
  package.json
  src/hooks/useSelector.ts
  src/util/throttle.ts
  tests/jest/util/throttle.test.ts
Labels: bug fix

#1410 remove unnecessary structuredClone() call, simplify SortActions
  src/view/plugin/sort/actions.ts
Labels: bug fix, performance

#1364 Added Swedish translation (sv_SE)
  l10n/sv_SE.ts
Labels: new feature

#1412 Fix deepEqual helper function
  l10n/index.ts
  l10n/sv_SE.ts
  package-lock.json
  package.json
  src/util/deepEqual.ts
  tests/jest/util/deepEqual.test.ts
Labels: bug fix
